kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-management
networking:
  apiServerAddress: 127.0.0.1
  # the default CNI will not be installed
  # disableDefaultCNI: true
  # kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
