---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserver
    version: v1
  name: httpserver-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      serviceAccountName: httpserver-default
      containers:
        - name: httpserver
          image: sarah4test/httpserver:latest@sha256:de2a3dffbd3ff510175f2819aadb9d5ad8edb74bde8dc5606baf148ec0d14292
          env:
            - name: VERSION
              value: "v1.0.1"
            - name: VERBOSE
              value: "2"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 15
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
          securityContext:
            runAsUser: 1000
      terminationGracePeriodSeconds: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserver
    version: v2
  name: httpserver-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v2
  template:
    metadata:
      labels:
        app: httpserver
        version: v2
    spec:
      serviceAccountName: httpserver-default
      containers:
        - name: httpserver
          image: sarah4test/httpserver:latest@sha256:de2a3dffbd3ff510175f2819aadb9d5ad8edb74bde8dc5606baf148ec0d14292
          env:
            - name: VERSION
              value: "v2.0.1"
            - name: VERBOSE
              value: "3"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 15
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
          securityContext:
            runAsUser: 1000
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver-default
  labels:
    account: httpserver
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app: httpserver
      service: httpserver
  name: httpserver
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: httpserver