{
 "title": "Httpserver dashboard",
 "tags": [ "myhttpserver" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (\n  rate(\n      httpserver_durations_histogram_seconds_sum {\n      }[5m]\n)) / sum (\n  rate(\n      httpserver_durations_histogram_seconds_count {\n      }[5m]\n  )\n)\n",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Total Request Duration by Handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(httpserver_durations_histogram_seconds_sum{}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median request duration by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  .5,\n  sum by (le, pod)(\n    rate(\n      httpserver_durations_histogram_seconds_bucket{\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Duration(last 5min)",
   "type": "timeseries",
   "description": "Total Request Duration over the last 5 minutes",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      httpserver_durations_histogram_seconds_bucket{\n      }[5m]\n    )\n  )\n)"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le)(\n    rate(\n      httpserver_durations_histogram_seconds_bucket{\n      }[5m]\n    )\n  )\n)"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      httpserver_durations_histogram_seconds_bucket{\n      }[5m]\n    )\n  )\n)"
    }
   ]
  }
 ]
}