---
- hosts: all
  pre_tasks:
    - name: Verify Ansible meets version requirements.
      ansible.builtin.assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this playbook."

- hosts: k-m-1
  become: true
  tasks:
    - name: Delete existing join command 
      file: 
        path: ./join-command-vars.yaml
        state: absent 
      delegate_to: 127.0.0.1
      become: false

    - import_tasks: tasks/container_runtime.yaml
    - import_tasks: tasks/k8s_install.yaml
    - import_tasks: tasks/k8s_ha.yaml
    - import_tasks: tasks/k8s_init.yaml
    - import_tasks: tasks/k8s_post_initjoin_masters.yaml

- hosts: ~k-m-[2-9]
  become: true
  tasks:
    - import_tasks: tasks/container_runtime.yaml
    - import_tasks: tasks/k8s_install.yaml
    - import_tasks: tasks/k8s_join.yaml
    - import_tasks: tasks/k8s_post_initjoin_masters.yaml

- hosts: k-n-*
  become: true
  tasks:
    - import_tasks: tasks/container_runtime.yaml
    - import_tasks: tasks/k8s_install.yaml
    - import_tasks: tasks/k8s_join.yaml